### ISSUE TITLE
MAC下貌似存在一个问题

### ISSUE THREAD

**Issue by 1ighttack** [tinyibird/HTTPServerGO#1]
我指定端口和目录，打开浏览器访问不到任何东西？
我使用的是下面的命令：
go run HTTPServerGO.go -p 6767 -d app
<img width="699" alt="图片" src="https://user-images.githubusercontent.com/71672296/235046430-5752152c-2c2c-4dfc-9674-506d534f8d2e.png">

**Comment by pho3n1x-web** [comment]
由于设计之初的目的，我并未考虑mac方面的兼容性，但是接下来的更新我会兼容mac的，后期或许可以打造成内网可用，那么mac兼容性就有必要考虑了，我会尽快解决的，放心

**Comment by 1ighttack** [comment]
好的，静候佳音

**Comment by pho3n1x-web** [comment]
已经解决了，其实不是不兼容MAC，只是在当初重构完http处理函数的时候有个错误处理忘记考虑无参数的情况了
